function formatTime(time: number) {
  const hours = Math.floor(time / 3600);
  const minutes = Math.floor((time % 3600) / 60);
  const seconds = time % 60;
  return `${hours.toString().padStart(2, "0")}:${minutes
    .toString()
    .padStart(2, "0")}:${seconds.toFixed(3).padStart(6, "0")}`;
}

export interface VttSegment {
  text: string;
  start: number;
  end: number;
}

export function createVtt(segments: VttSegment[]): string {
  const webvtt: string[] = [
    "WEBVTT - Auto-generated by https://github.com/dtinth/autosub",
  ];

  for (const segment of segments) {
    webvtt.push("");
    webvtt.push(`${formatTime(segment.start)} --> ${formatTime(segment.end)}`);
    webvtt.push(segment.text);
  }
  webvtt.push("");

  return webvtt.join("\n");
}
